version: "3.9"
services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freemyip-updater
    restart: unless-stopped
    networks:
      - podman

networks:
  podman:
    external: true
